<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empleados[
    <!ELEMENT empleados (empleado)>
    <!ELEMENT empleado (nombre,apellido,edad,departamento,cargo)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT edad (#PCDATA)>
    <!ELEMENT departamentoe (#PCDATA)>
    <!ELEMENT cargo (#PCDATA)>
]>

<empleados>
    <empleado id="1">
        <nombre>ana</nombre>
        <apellido>Garc√≠a</apellido>
        <edad>30</edad>
        <departamento>Ventas</departamento>
        <cargo>Ejecutivo de ventas</cargo>        
    </empleado>
    <empleado id="2">
        <nombre>Luis</nombre>
        <apellido>Rodriguez</apellido>
        <edad>45</edad>
        <departamento>Finanzas</departamento>
        <cargo>Analista financiero</cargo>
    </empleado>
    <empleado id="3">
        <nombre>Maria</nombre>
        <apellido>Lopez</apellido>
        <edad>28</edad>
        <departamento>Marketing</departamento>
        <cargo>Especialista en redes Sociales</cargo>
    </empleado>
</empleados>